<?
$aMenuLinks = array(
    array(
        'о нас',
        '/about/',
        array(),
        array(),
        ''
    ),
    array(
        'рецепты',
        '/recipes/',
        array(),
        array(),
        ''
    ),
    array(
        'возможности',
        '#',
        array(),
        array(),
        ''
    ),
    array(
        'товары для розницы',
        '/catalog/?arrFilter_pf%5BDIRECTION%5D=10&set_filter=Y',
        array(),
        array(),
        ''
    ),
    array(
        'топ-10 продукции',
        '#',
        array(),
        array(),
        ''
    ),
    array(
        'события',
        '/events/',
        array(),
        array(),
        ''
    ),
    array(
        'упаковка',
        '#',
        array(),
        array(),
        ''
    ),
    array(
        'преимущества',
        '#',
        array(),
        array(),
        ''
    ),
    array(
        'для сегмента HoReCa',
        '/catalog/?arrFilter_pf%5BDIRECTION%5D=11&set_filter=Y',
        array(),
        array(),
        ''
    ),
    array(
        'торговые марки',
        '/brands/',
        array(),
        array(),
        ''
    ),
    array(
        'предложения',
        '#',
        array(),
        array(),
        ''
    ),
    array(
        'новинки',
        '#',
        array(),
        array(),
        ''
    ),
    array(
        'что прозводим',
        '/catalog/',
        array(),
        array(),
        ''
    ),
    array(
        'для производства',
        '/catalog/?arrFilter_pf%5BDIRECTION%5D=12&set_filter=Y',
        array(),
        array(),
        ''
    ),
);