<?
$aMenuLinks = array(
    array(
        'о нас',
        '/about/',
        array(),
        array(),
        ''
    ),
    array(
        'рецепты',
        '/recipes/',
        array(),
        array(),
        ''
    ),
    array(
        'возможности',
        '#',
        array(),
        array(),
        ''
    ),
    array(
        'товары для розницы',
        '/direction/tovary-dlya-roznitsy/',
        array(),
        array(),
        ''
    ),
    array(
        'топ-10 продукции',
        '#',
        array(),
        array(),
        ''
    ),
    array(
        'события',
        '/events/',
        array(),
        array(),
        ''
    ),
    array(
        'эксклюзивы',
        '/exclusive/',
        array(),
        array(),
        ''
    ),
    array(
        'преимущества',
        '#',
        array(),
        array(),
        ''
    ),
    array(
        'для сегмента HoReCa',
        '/direction/produkty-dlya-horeca/',
        array(),
        array(),
        ''
    ),
    array(
        'торговые марки',
        '/brands/',
        array(),
        array(),
        ''
    ),
    array(
        'предложения',
        '#',
        array(),
        array(),
        ''
    ),
    array(
        'новинки',
        '#',
        array(),
        array(),
        ''
    ),
    array(
        'что прозводим',
        '/catalog/',
        array(),
        array(),
        ''
    ),
    array(
        'для производства',
        '/direction/syre-dlya-proizvodstva/',
        array(),
        array(),
        ''
    ),
);